# Generated by Django 5.1.4 on 2024-12-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookapp', '0004_delete_logintable_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='quantity',
            field=models.IntegerField(default=1234),
            preserve_default=False,
        ),
    ]
